apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job-container
              image: cron-job-image
              command:
                - echo
                - "Hello, Kubernetes!"
          restartPolicy: OnFailure