apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
    - name: my-app-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
