apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: main-container
      image: main-image
      volumeMounts:
        - name: data-volume
          mountPath: /data
    - name: sidecar-container
      image: sidecar-image
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: data-volume
      emptyDir: {}
    - name: config-volume
      emptyDir: {}
 
  